name: audiobook_e_library
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^15.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  syncfusion_flutter_pdfviewer: ^29.1.40
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  audioplayers: ^6.4.0
  provider: ^6.1.5
  just_audio: ^0.10.1
  lottie: ^3.3.1
  flutter_pdfview: ^1.4.0+1
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  percent_indicator: ^4.2.5
  flutter_cached_pdfview: ^0.4.3
  flutter_custom_tabs: ^2.4.0
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.4
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

